### ISSUE TITLE
인과추론으로 네트워킹 행사 피드백사항

### ISSUE THREAD

**Issue by ehddnr301** [pseudolab/pseudolab-frontend#14]
# To-Do

- [x] 나와 네트워킹한 사람 조회기능 (닉네임, 정보?) [심소현님]
- [x] 최근 보내준 단어 표시기능 (방금 보내준 단어가 무엇인지 하이라이팅) [오성민님]
- [x] 빈 닉네임 혹은 키워드로 시작 불가기능 [버그제보 다수...]
- [x] #17
