### ISSUE TITLE
빙고 잔여 작업 리스트

### ISSUE THREAD

**Issue by ehddnr301** [pseudolab/pseudolab-frontend#6]
# To-Do List

- [x] 단어 위치 Random 배치
- [x] 반응형 프론트 화면
- [x] 빙고판 디자인 개선
- [ ] 유저쪽 작업완료시 연동 코드변경

**Comment by ehddnr301** [comment]
유저 연동작업은 추후에 반영하도록 하겠습니다.
